/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.formularios;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
/**
 *
 * @author Tarcísio
 */
public class JFMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
        
        new Thread(){
@Override
public void run (){
for(;;){
dataEhora();

try {
sleep(1_000);

} catch (InterruptedException ie) {
ie.printStackTrace();
}

}
}

}.start();

}
@SuppressWarnings("deprecation")
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jhora = new javax.swing.JLabel();
        jdata = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        jMenuItemCondomino = new javax.swing.JMenuItem();
        jMenuItemApartamento = new javax.swing.JMenuItem();
        jMenuItemBloco = new javax.swing.JMenuItem();
        jMenuItemVeiculo = new javax.swing.JMenuItem();
        jMenuItemPrestador = new javax.swing.JMenuItem();
        jMenuItemVisitante = new javax.swing.JMenuItem();
        jMenuItemOcorrencia = new javax.swing.JMenuItem();
        jMenuItemfuncionario = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemCondominio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemFechar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones telas/fundo.png"))); // NOI18N
        jLabel1.setIconTextGap(6);
        jDesktop.add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Seja bem-vindo ao sistema Condomínio Express");

        jhora.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jhora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones painel/relogio.png"))); // NOI18N
        jhora.setText("jLabel3");

        jdata.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones painel/calendario.png"))); // NOI18N
        jdata.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jdata)
                .addGap(27, 27, 27)
                .addComponent(jhora)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jhora)
                    .addComponent(jdata))
                .addContainerGap())
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/menu.png"))); // NOI18N
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        Menu.setLabel("Iniciar   |");

        jMenuItemCondomino.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItemCondomino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/condomino.png"))); // NOI18N
        jMenuItemCondomino.setText("Condômino");
        jMenuItemCondomino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCondomino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCondominoActionPerformed(evt);
            }
        });
        Menu.add(jMenuItemCondomino);

        jMenuItemApartamento.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItemApartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/Apartamento.png"))); // NOI18N
        jMenuItemApartamento.setText("Apartamento");
        jMenuItemApartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemApartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApartamentoActionPerformed(evt);
            }
        });
        Menu.add(jMenuItemApartamento);

        jMenuItemBloco.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItemBloco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/bloco.png"))); // NOI18N
        jMenuItemBloco.setText("Bloco");
        jMenuItemBloco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemBloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBlocoActionPerformed(evt);
            }
        });
        Menu.add(jMenuItemBloco);

        jMenuItemVeiculo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItemVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/veiculo.png"))); // NOI18N
        jMenuItemVeiculo.setText("Veículo");
        jMenuItemVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVeiculoActionPerformed(evt);
            }
        });
        Menu.add(jMenuItemVeiculo);

        jMenuItemPrestador.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItemPrestador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/prestador.png"))); // NOI18N
        jMenuItemPrestador.setText("Prestador de serviço");
        jMenuItemPrestador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemPrestador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrestadorActionPerformed(evt);
            }
        });
        Menu.add(jMenuItemPrestador);

        jMenuItemVisitante.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItemVisitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/visitante.png"))); // NOI18N
        jMenuItemVisitante.setText("Visitante");
        jMenuItemVisitante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisitanteActionPerformed(evt);
            }
        });
        Menu.add(jMenuItemVisitante);

        jMenuItemOcorrencia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItemOcorrencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/ocorrencias.png"))); // NOI18N
        jMenuItemOcorrencia.setText("Ocorrência");
        jMenuItemOcorrencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOcorrenciaActionPerformed(evt);
            }
        });
        Menu.add(jMenuItemOcorrencia);

        jMenuItemfuncionario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItemfuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/funcionario.png"))); // NOI18N
        jMenuItemfuncionario.setText("Funcionário");
        jMenuItemfuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemfuncionarioActionPerformed(evt);
            }
        });
        Menu.add(jMenuItemfuncionario);

        jMenuItemUsuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/usuario.png"))); // NOI18N
        jMenuItemUsuario.setText("Usuário");
        jMenuItemUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        Menu.add(jMenuItemUsuario);

        jMenuItemCondominio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItemCondominio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/condominio.png"))); // NOI18N
        jMenuItemCondominio.setText("Condomínio");
        jMenuItemCondominio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCondominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCondominioActionPerformed(evt);
            }
        });
        Menu.add(jMenuItemCondominio);

        jMenuBar1.add(Menu);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/ajuda.png"))); // NOI18N
        jMenu2.setText("Ajuda   |");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jMenuItemSobre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/sobre.png"))); // NOI18N
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSobre);

        jMenuBar1.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/sistema.png"))); // NOI18N
        jMenu1.setText("Sistema   |");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jMenu1.setInheritsPopupMenu(true);
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemFechar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItemFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/imagens/icones menu/Logout.png"))); // NOI18N
        jMenuItemFechar.setText("Sair");
        jMenuItemFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFecharActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFechar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(800, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
 
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItemFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFecharActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jMenuItemFecharActionPerformed

    private void jMenuItemCondominoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCondominoActionPerformed
  JFCONCondomino CONCondominio = new JFCONCondomino();
  jDesktop.add(CONCondominio);
  CONCondominio.setVisible(true);
  CONCondominio.setPosicao(); 
    }//GEN-LAST:event_jMenuItemCondominoActionPerformed

    private void jMenuItemApartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApartamentoActionPerformed
  JFCONApartamento CONApartamento = new JFCONApartamento();
  jDesktop.add(CONApartamento);
  CONApartamento.setVisible(true);
  CONApartamento.setPosicao(); 
    }//GEN-LAST:event_jMenuItemApartamentoActionPerformed

    private void jMenuItemBlocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBlocoActionPerformed
  JFCONBloco CONBloco = new JFCONBloco();
  jDesktop.add(CONBloco);
  CONBloco.setVisible(true);
  CONBloco.setPosicao(); 
    }//GEN-LAST:event_jMenuItemBlocoActionPerformed

    private void jMenuItemVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVeiculoActionPerformed
  JFCONVeiculo CONVeiculo = new JFCONVeiculo();
  jDesktop.add(CONVeiculo);
  CONVeiculo.setVisible(true);
  CONVeiculo.setPosicao();   
    }//GEN-LAST:event_jMenuItemVeiculoActionPerformed

    private void jMenuItemPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrestadorActionPerformed
  JFCONPrestador CONPrestador = new JFCONPrestador();
  jDesktop.add(CONPrestador);
  CONPrestador.setVisible(true);
  CONPrestador.setPosicao();   
        
    }//GEN-LAST:event_jMenuItemPrestadorActionPerformed

    private void jMenuItemVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisitanteActionPerformed
  JFCONVisitante CONVisitante = new JFCONVisitante();
  jDesktop.add(CONVisitante);
  CONVisitante.setVisible(true);
  CONVisitante.setPosicao(); 
    }//GEN-LAST:event_jMenuItemVisitanteActionPerformed

    private void jMenuItemOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOcorrenciaActionPerformed
  JFCONOcorrencia CONOcorrencia = new JFCONOcorrencia();
  jDesktop.add(CONOcorrencia);
  CONOcorrencia.setVisible(true);
  CONOcorrencia.setPosicao(); 
    }//GEN-LAST:event_jMenuItemOcorrenciaActionPerformed

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
   JFCONUsuario CONUsuario = new JFCONUsuario();
  jDesktop.add(CONUsuario);
 CONUsuario.setVisible(true);
  CONUsuario.setPosicao();
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void jMenuItemfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemfuncionarioActionPerformed
JFCONFuncionario CONFuncionario = new JFCONFuncionario();
jDesktop.add(CONFuncionario);
CONFuncionario.setVisible(true);
CONFuncionario.setPosicao();
    }//GEN-LAST:event_jMenuItemfuncionarioActionPerformed

    private void jMenuItemCondominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCondominioActionPerformed
JFCADCondominio CADCondominio = new JFCADCondominio();
jDesktop.add(CADCondominio);
CADCondominio.setVisible(true);
CADCondominio.setPosicao();
    }//GEN-LAST:event_jMenuItemCondominioActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
JFInfo Info = new JFInfo ();
jDesktop.add(Info);
Info.setVisible(true);
Info.setPosicao();
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    
public void dataEhora(){
Calendar cal = new GregorianCalendar();
int dia = cal.get(Calendar.DAY_OF_MONTH);
int mes = cal.get(Calendar.MONTH);
int ano = cal.get(Calendar.YEAR);
int hora = cal.get (Calendar.HOUR_OF_DAY);     
int minuto = cal.get (Calendar.MINUTE);  
int segundo = cal.get (Calendar.SECOND);

jdata.setText("Data: "+dia+"/"+(mes+1)+"/"+ano);
jhora.setText("Hora: "+hora+":"+minuto+":"+segundo);
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    public static javax.swing.JDesktopPane jDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemApartamento;
    private javax.swing.JMenuItem jMenuItemBloco;
    private javax.swing.JMenuItem jMenuItemCondominio;
    private javax.swing.JMenuItem jMenuItemCondomino;
    private javax.swing.JMenuItem jMenuItemFechar;
    private javax.swing.JMenuItem jMenuItemOcorrencia;
    private javax.swing.JMenuItem jMenuItemPrestador;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenuItem jMenuItemVeiculo;
    private javax.swing.JMenuItem jMenuItemVisitante;
    private javax.swing.JMenuItem jMenuItemfuncionario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jdata;
    private javax.swing.JLabel jhora;
    // End of variables declaration//GEN-END:variables
}
